cities-settings:
  cities:
    - name: Kazan
    - name: Tolyatti
    - name: Ottava
    - name: Sydney

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather_forecast
    username: postgres
    password: 16s11w86d

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    weather.example.weatherNow: info
    org:
      springframework: ${LOG:info}
  file:
    name: logs/log

cron:
  saveMeasurements: "0 * * * * *"