drop table if exists measurement;
drop table if exists city;

create table city
(
    city_id   int generated by default as identity primary key,
    city_name varchar(50) check ( char_length(city_name) >= 3) not null UNIQUE
);


create table measurement
(
    measurement_id   int generated by default as identity primary key,
    city_id          int REFERENCES city (city_id) not null,
    temperature      double precision,
    measurement_date timestamp(6)

);


insert into city(city_id, city_name)
values (100, 'Moscow'),
       (200, 'Ottava');

insert into measurement(measurement_id,city_id,temperature,measurement_date)
values (100, 100, 25.0, '2024-10-10 10:33:00.803206'),
       (101, 200, 12.3, '2023-05-12 10:33:00.803206');