create schema weather_forecast;
create table city
(
    city_id   int generated by default as identity primary key,
    city_name varchar(50) check ( char_length(city_name) >= 3) not null UNIQUE
);

create table measurement
(
    measurement_id   int generated by default as identity primary key,
    city_id          int REFERENCES city (city_id) not null,
    temperature      double precision,
    measurement_date timestamp(6)

);